behaviors:
  CaroAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      learning_rate_schedule: linear
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    checkpoint_interval: 250000
    keep_checkpoints: 10
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000

engine_settings:
  time_scale: 20
  target_frame_rate: -1
  no_graphics: false

checkpoint_settings:
  run_id: caro_ai_v2
  results_dir: results
  resume: false
  force: false
  train_model: true
  inference: false
